/* eslint-disable max-len, global-require */
export default new Map([
  ['/images/dashboard/V2/transactions.png?v6.4.1', require('./transactions.png')],
  ['/images/dashboard/V2/items_app.png?v6.4.1', require('./items_app.png')],
  ['/images/dashboard/V2/dashboard.png?v6.4.1', require('./dashboard.png')],
  ['/images/dashboard/V2/communication.png?v6.4.1', require('./communication.png')],
  ['/images/dashboard/V2/my_stores.png?v6.4.1', require('./my_stores.png')],
  ['/images/dashboard/V2/live_support.png?v6.4.1', require('./live_support.png')],
  ['/images/dashboard/V2/settings.png?v6.4.1', require('./settings.png')],
  ['/media/cache/channels.list/e-conomic.png', require('./e-conomic.png')],
  ['/media/cache/channels.list/overlay.png', require('./overlay.png')],
  ['/images/dashboard/V2/add_channel.png?v6.4.1', require('./add_channel.png')],
  ['/images/dashboard/V2/payment_options.png?v6.4.1', require('./payment_options.png')],
  ['/images/dashboard/V2/contacts_app.png?v6.4.1', require('./contacts_app.png')],
  ['/images/dashboard/V2/marketing_ad_app.png?v6.4.1', require('./marketing_ad_app.png')],
  ['/media/cache/channels.list/debitoor.png', require('./debitoor.png')],
  ['/micro/trust/frontend/logo.png', require('./logo.png')],
  ['/images/dashboard/V2/statistics.png?v6.4.1', require('./statistics.png')],
  ['/media/cache/channels.list/marketing.png', require('./marketing.png')],
  ['/media/cache/channels.list/finance_express.png', require('./finance_express.png')],
]);