/* eslint-disable max-len, global-require */
export default new Map([
  ['/images/dashboard/V2/transactions.png', require('./transactions.png')],
  ['/images/dashboard/V2/items_app.png', require('./items_app.png')],
  ['/images/dashboard/V2/dashboard.png', require('./dashboard.png')],
  ['/images/dashboard/V2/communication.png', require('./communication.png')],
  ['/images/dashboard/V2/my_stores.png', require('./my_stores.png')],
  ['/images/dashboard/V2/live_support.png', require('./live_support.png')],
  ['/images/dashboard/V2/settings.png', require('./settings.png')],
  ['/media/cache/channels.list/e-conomic.png', require('./e-conomic.png')],
  ['/media/cache/channels.list/overlay.png', require('./overlay.png')],
  ['/images/dashboard/V2/add_channel.png', require('./add_channel.png')],
  ['/images/dashboard/V2/payment_options.png', require('./payment_options.png')],
  ['/images/dashboard/V2/contacts_app.png', require('./contacts_app.png')],
  ['/images/dashboard/V2/marketing_ad_app.png', require('./marketing_ad_app.png')],
  ['/media/cache/channels.list/debitoor.png', require('./debitoor.png')],
  ['/micro/trust/frontend/logo.png', require('./logo.png')],
  ['/images/dashboard/V2/statistics.png', require('./statistics.png')],
  ['/media/cache/channels.list/marketing.png', require('./marketing.png')],
  ['/media/cache/channels.list/finance_express.png', require('./finance_express.png')],
  ['/images/dashboard/purchases.png', require('./purchases.png')],
  ['/images/dashboard/communication.png', require('./communication.png')],
  ['/images/dashboard/settings.png', require('./settings.png')],
  ['/media/cache/channels.list/pos.png', require('./pos.png')],
]);