import generatedConfig from './_autogenerated';

export class Config {
  siteUrl: string;
  api: {
    baseUrl: string;
    clientId: string;
    clientSecret: string;
  };

  constructor(data) {
    Object.assign(this, data);
  }
}

export default new Config(generatedConfig);