fastlane_version "1.109.0"

def is_mac?
  (/darwin/ =~ RUBY_PLATFORM) != nil
end

def publish_to_fabric(values, options = {})
  emails = values[:email] ? values[:email] : ['megahertz@l96.ru']
  groups = values[:group] ? nil : nil

  defaults = {
	api_token: '48b58dc9c7da86d72ed314088b46e42f1a0b78ff',
	build_secret: 'd81977fd8d8dd7e21bfac54c7952d0136b24603cf554084ed78b9cafed2d9aed',
	emails: emails,
	groups: groups,
	notes: changelog_from_git_commits(
	  commits_count: 5,
	  pretty: '%h %an %ar %n%s %+b %n'
	),
	notifications: true
  }

  crashlytics(defaults.merge(options))
end

default_platform is_mac? ? :ios : :android

platform :ios do
  #
  # Learn more here: https://github.com/fastlane/setups/blob/master/samples-ios/distribute-beta-build.md 🚀
  #
  desc 'Publish a new IOS beta through fabric.io'
  lane :beta do |values|
    gym(
      scheme: 'PayeverMobile',
      workspace: 'ios/PayeverMobile.xcworkspace',
      export_method: 'ad-hoc',
      output_directory: 'fastlane/build/ios',
      output_name: 'payever.ipa'   
    )
	publish_to_fabric(values, ipa_path: 'fastlane/build/ios/payever.ipa')
  end
end

platform :android do
  desc 'Publish a new Android beta through fabric.io'
  lane :beta do |values|
    gradle(task: 'clean', project_dir: "android/")
    gradle(task: "assemble", build_type: "Release", project_dir: "android/")
	publish_to_fabric(values)
  end
end