fastlane_version "1.109.0"

default_platform :ios

platform :ios do
  #
  # Learn more here: https://github.com/fastlane/setups/blob/master/samples-ios/distribute-beta-build.md 🚀
  #
  lane :beta do |values|
    # Fabric generated this lane for deployment to Crashlytics Beta
    # set 'export_method' to 'ad-hoc' if your Crashlytics Beta distribution uses ad-hoc provisioning

    ENV["PROVISIONING_PROFILE_TARGET1"] = "35c960f7-2f88-4b28-b80f-302336e8ad5d"    
  
    gym(
      scheme: 'PayeverMobile',
      export_method: "ad-hoc"      
    )

    emails = values[:test_email] ? values[:test_email] : ['megahertz@l96.ru'] # You can list more emails here
    groups = values[:test_email] ? nil : nil # You can define groups on the web and reference them here

    crashlytics(api_token: '48b58dc9c7da86d72ed314088b46e42f1a0b78ff',
             build_secret: 'd81977fd8d8dd7e21bfac54c7952d0136b24603cf554084ed78b9cafed2d9aed',
                   emails: emails,
                   groups: groups,
                    notes: 'Distributed with fastlane', # Check out the changelog_from_git_commits action
            notifications: true) # Should this distribution notify your testers via email?

    # for all available options run `fastlane action crashlytics`

    # You can notify your team in chat that a beta build has been uploaded
    # slack(
    #   slack_url: "https://hooks.slack.com/services/YOUR/TEAM/INFO"
    #   channel: "beta-releases",
    #   message: "Successfully uploaded a beta release - see it at https://fabric.io/_/beta"
    # )
  end
end
