/* eslint-disable global-require, max-len */

//noinspection JSUnresolvedVariable
export default {
  'auth.Login': require('./modules/auth/screens/Login').default,
  'auth.Register': require('./modules/auth/screens/Register').default,
  'auth.RegisterWithEmail': require('./modules/auth/screens/RegisterWithEmail').default,
  'auth.RegCompletedDialog': require('./modules/auth/screens/RegCompletedDialog').default,
  'auth.ResetPassword': require('./modules/auth/screens/ResetPassword').default,
  'communication.StartNewConversations': require('./modules/communication/screens/StartNewConversations').default,
  'communication.AddGroup': require('./modules/communication/screens/AddGroup').default,
  'communication.AddMemberToGroup': require('./modules/communication/screens/AddMemberToGroup').default,
  'communication.Chat': require('./modules/communication/screens/Chat').default,
  'communication.Contacts': require('./modules/communication/screens/Contacts').default,
  'communication.ConversationSettings': require('./modules/communication/screens/ConversationSettings').default,
  'communication.EditMessage': require('./modules/communication/screens/EditMessage').default,
  'communication.GeneralSettings': require('./modules/communication/screens/GeneralSettings').default,
  'communication.GroupSettings': require('./modules/communication/screens/GroupSettings').default,
  'communication.ImageMedia': require('./modules/communication/screens/ImageMedia').default,
  'contacts.BusinessContacts': require('./modules/contacts/screens/BusinessContacts').default,
  'contacts.AddNewCustomerContact': require('./modules/contacts/screens/AddNewCustomerContact').default,
  'core.AllWebView': require('./modules/core/screens/AllWebView').default,
  'core.Debug': require('./modules/core/screens/Debug').default,
  'core.DeepLinksPopup': require('./modules/core/screens/DeepLinksPopup').default,
  'core.ErrorPage': require('./modules/core/screens/ErrorPage').default,
  'core.LaunchScreen': require('./modules/core/screens/LaunchScreen').default,
  'core.LiveChat': require('./modules/core/screens/LiveChat').default,
  'core.PushNotification': require('./modules/core/screens/PushNotification').default,
  'core.SideMenu': require('./modules/core/screens/SideMenu').default,
  'core.WebView': require('./modules/core/screens/WebView').default,
  'dashboard.AddNewBusiness': require('./modules/dashboard/screens/AddNewBusiness').default,
  'dashboard.ChooseAccount': require('./modules/dashboard/screens/ChooseAccount').default,
  'dashboard.Dashboard': require('./modules/dashboard/screens/Dashboard').default,
  'dashboard.Private': require('./modules/dashboard/screens/Private').default,
  'dashboard.ProfileInfo': require('./modules/dashboard/screens/ProfileInfo').default,
  'dashboard.ProfileInfoWebView': require('./modules/dashboard/screens/ProfileInfoWebView').default,
  'dashboard.Search': require('./modules/dashboard/screens/Search').default,
  'marketing.BuyOffer': require('./modules/marketing/screens/BuyOffer').default,
  'marketing.CreateOffer': require('./modules/marketing/screens/CreateOffer').default,
  'marketing.ViewOffer': require('./modules/marketing/screens/ViewOffer').default,
  'pos.Terminal': require('./modules/pos/screens/Terminal').default,
};